name: sensor-server

services:
  influxdb:
    image: influxdb:alpine
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin-token
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=db-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=db-password
      - DOCKER_INFLUXDB_INIT_ORG=sensor-org
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor-data-bucket
    ports:
      - "8086:8086"

  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - influxdb
    restart: on-failure
